#!/bin/sh

set -e -x

cd ${HOME}
ls
echo $PATH
export PATH="${WORK}/clang/bin:${WORK}/gcc/bin:${PATH}"
echo $PATH
export ARCH=arm
export CROSS_COMPILE=arm-linux-androideabi-
export CC=clang
export HOSTCC=clang
export CLANG_TRIPLE=arm-linux-gnueabi-
rm -rf out
mkdir -p out
make O=out ARCH=arm CC=clang HOSTCC=clang CLANG_TRIPLE=arm-linux-gnueabi- CROSS_COMPILE=arm-linux-androidkernel- clean
make O=out ARCH=arm CC=clang HOSTCC=clang CLANG_TRIPLE=arm-linux-gnueabi- CROSS_COMPILE=arm-linux-androidkernel- mrproper
make O=out ARCH=arm CC=clang HOSTCC=clang CLANG_TRIPLE=arm-linux-gnueabi- CROSS_COMPILE=arm-linux-androidkernel- a02_defconfig
make O=out ARCH=arm CC=clang HOSTCC=clang CLANG_TRIPLE=arm-linux-gnueabi- CROSS_COMPILE=arm-linux-androidkernel- -j$(nproc --all)
